### PR TITLE
Add cache management

### PR DESCRIPTION
**Pull request by danielegiorgis**
**Admin page for cache management**

With that you can 
- Delete all the cache
- Clear the cache of individual files without clearing all

### CODE REVIEW

**Comment by pioneerskies** [comment]
It seems so sweet. I'll review it ASAP. Could I just ask you to rebase or clean up the branch? I'm seeing the majority of commits are extraneous. TIA <3

**Comment by danielegiorgis** [comment]
Rebased

**Comment by pioneerskies** [comment]
Extraneous commits persists :( I cannot merge them 'cos they revert some updates into my branch :(

**Comment by danielegiorgis** [comment]
I did the same operations made for the ```bugfix_static_rendering``` branch. I believe you are now able to merge

**Pull request merged**
